# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create(username: "Guest", password:"password")
User.create(username: "PPMD", password:"Kreygasm")
User.create(username: "mang0", password:"mangoW")
User.create(username: "Armada", password:"Stitch")
User.create(username: "Hungrybox", password:"ledgecamp")
User.create(username: "Leffen", password:"zipboys")
User.create(username: "Mew2King", password:"lolm2k")
User.create(username: "Plup", password:"shielddrop")
User.create(username: "Axe", password:"tailspike")
User.create(username: "Westballz", password:"blipblip")
User.create(username: "Shroomed", password:"upsmash")
User.create(username: "PewPewU", password:"ppuFilth")
User.create(username: "SFAT", password:"theJVB")
User.create(username: "Chillin", password:"ogMyBGuy")
User.create(username: "Zhu", password:"WomboCombo")
User.create(username: "Phil", password:"AintFalco")
User.create(username: "HMW", password:"GetYoAssWhooped")
User.create(username: "Fox", password:"drillshine")
User.create(username: "Falco", password:"uptiltbair")
User.create(username: "Marth", password:"chaingrab")
User.create(username: "Sheik", password:"techchase")
User.create(username: "Peach", password:"turnip")
User.create(username: "Jigglypuff", password:"bairrest")
User.create(username: "IceClimbers", password:"wobble")
User.create(username: "CFalcon", password:"stompknee")
User.create(username: "Luigi", password:"wavedash")
User.create(username: "Mario", password:"mangoScorp")
User.create(username: "SoulOfCinder", password:"Cinder")
User.create(username: "Artorias", password:"SifSif")
User.create(username: "AbyssWatchers", password:"Farron")
User.create(username: "Aldrich", password:"Gwyndolin")
User.create(username: "Gundyr", password:"Champion")

Project.create(title: "Save the Whales", image_url: "", description: "", funding_goal: 20000, end_date: "November 30th, 2017")

Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 1, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 1, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 1, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 1, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 1, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 1, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 2, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 2, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 2, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 2, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 2, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 2, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 3, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 3, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 3, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 3, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 3, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 3, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 4, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 4, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 4, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 4, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 4, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 4, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 5, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 5, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 5, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 5, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 5, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 5, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 6, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 6, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 6, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 6, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 6, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 6, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 7, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 7, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 7, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 7, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 7, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 7, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 8, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 8, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 8, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 8, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 8, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 8, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 9, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 9, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 9, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 9, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 9, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 9, amount: 300)
Reward.create(name: "Thanks", description: "Our heartfelt thanks for your contribution.", project_id: 10, amount: 1)
Reward.create(name: "Name In Credits", description: "We'll put your name in the credits to remember your help.", project_id: 10, amount: 5)
Reward.create(name: "Personal Email", description: "We'll send you a personalized email to appreciate your support.", project_id: 10, amount: 10)
Reward.create(name: "T-Shirt", description: "A limited-edition, all-cotton Save the Whales t-shirt.", project_id: 10, amount: 25)
Reward.create(name: "Deluxe Package", description: "All of the above, plus a coffee mug.", project_id: 10, amount: 100)
Reward.create(name: "Supreme Package", description: "All of the above, plus a life-size whale plush.", project_id: 10, amount: 300)

Rewarding.create(user_id: 1, reward_id: 1)
Rewarding.create(user_id: 1, reward_id: 2)
Rewarding.create(user_id: 1, reward_id: 3)
Rewarding.create(user_id: 1, reward_id: 4)
Rewarding.create(user_id: 2, reward_id: 6)
Rewarding.create(user_id: 3, reward_id: 6)
Rewarding.create(user_id: 4, reward_id: 6)
Rewarding.create(user_id: 5, reward_id: 6)
Rewarding.create(user_id: 5, reward_id: 7)
Rewarding.create(user_id: 5, reward_id: 8)
Rewarding.create(user_id: 5, reward_id: 9)
Rewarding.create(user_id: 5, reward_id: 10)

Backing.create(project_id: 1, user_id: 1, amount: 100)

Tag.create(name: "Games")
Tag.create(name: "Environment")
Tag.create(name: "Causes")
Tag.create(name: "Tech")
Tag.create(name: "Lifestyle")
Tag.create(name: "Activities")
